// ─── Mock Data for Dashboard (no Supabase required) ───────────────────────
// Replace these with real Supabase calls once credentials are configured.

export const MOCK_BLOGS = [
  {
    id: '1',
    title: 'How Salesforce CRM Transforms Sales Teams',
    slug: 'salesforce-crm-transforms-sales-teams',
    excerpt: 'Discover how leading enterprises use Salesforce to streamline their sales pipeline.',
    category: 'Salesforce Consulting',
    author: 'Zuhaib Ahmed',
    status: 'published',
    cover_image_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800',
    meta_title: 'Salesforce CRM for Sales Teams | Pentacloud',
    meta_description: 'Learn how Salesforce CRM can transform your sales operations with automation and insights.',
    og_image_url: '',
    content: '<p>Salesforce is the world\'s #1 CRM platform...</p>',
    created_at: '2026-08-10T09:00:00Z',
    updated_at: '2026-08-15T12:00:00Z',
    published_at: '2026-08-10T09:00:00Z',
  },
  {
    id: '2',
    title: 'Zoho One vs Microsoft 365: Which Suite Fits Your Business?',
    slug: 'zoho-one-vs-microsoft-365',
    excerpt: 'A detailed comparison of two of the most popular business productivity suites.',
    category: 'Zoho Service',
    author: 'Pentacloud Team',
    status: 'published',
    cover_image_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
    meta_title: 'Zoho One vs Microsoft 365 | Pentacloud',
    meta_description: '',
    og_image_url: '',
    content: '<p>Choosing between Zoho One and Microsoft 365...</p>',
    created_at: '2026-08-05T10:00:00Z',
    updated_at: '2026-08-05T10:00:00Z',
    published_at: '2026-08-05T10:00:00Z',
  },
  {
    id: '3',
    title: 'Top 5 Cloud Migration Mistakes to Avoid in 2026',
    slug: 'cloud-migration-mistakes-2026',
    excerpt: 'Moving to the cloud? Here are the pitfalls that trip up most businesses.',
    category: 'Cloud Solution',
    author: 'Zuhaib Ahmed',
    status: 'draft',
    cover_image_url: '',
    meta_title: '',
    meta_description: '',
    og_image_url: '',
    content: '<p>Cloud migration is complex...</p>',
    created_at: '2026-08-18T08:00:00Z',
    updated_at: '2026-08-18T08:00:00Z',
    published_at: null,
  },
  {
    id: '4',
    title: 'How Salesforce CRM Transforms Sales Teams (Duplicate)',
    slug: 'salesforce-crm-transforms-sales-teams-copy',
    excerpt: 'Discover how leading enterprises use Salesforce to streamline their sales pipeline.',
    category: 'Salesforce Consulting',
    author: 'Zuhaib Ahmed',
    status: 'published',
    cover_image_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800',
    meta_title: 'Salesforce CRM for Sales Teams | Pentacloud',
    meta_description: 'Learn how Salesforce CRM can transform your sales operations with automation and insights.',
    og_image_url: '',
    content: '<p>Salesforce is the world\'s #1 CRM platform...</p>',
    created_at: '2026-08-20T09:00:00Z',
    updated_at: '2026-08-20T12:00:00Z',
    published_at: '2026-08-20T09:00:00Z',
  },
];

export const MOCK_LEADS = [
  {
    id: '1',
    name: 'Rahul Mehta',
    email: 'rahul@techcorp.in',
    phone: '+91 98765 43210',
    message: 'Company: TechCorp India\nInterested Service: Salesforce Consulting',
    source_page: 'Contact Us Page',
    status: 'new',
    created_at: '2026-08-18T07:30:00Z',
  },
  {
    id: '2',
    name: 'Sarah Al Mansoori',
    email: 'sarah@dubaigroup.ae',
    phone: '+971 50 123 4567',
    message: 'Company: Dubai Group\nInterested Service: Zoho Services',
    source_page: 'Zoho Services Page',
    status: 'contacted',
    created_at: '2026-08-16T11:00:00Z',
  },
  {
    id: '3',
    name: 'James Wilson',
    email: 'james@globalcorp.com',
    phone: null,
    message: 'Company: Global Corp\nInterested Service: Cloud Solutions',
    source_page: 'Contact Us Page',
    status: 'closed',
    created_at: '2026-08-12T14:00:00Z',
  },
];

export const MOCK_CAREER_APPLICATIONS = [
  {
    id: '1',
    name: 'Priya Sharma',
    email: 'priya.sharma@gmail.com',
    phone: '+91 99887 76655',
    position: 'Salesforce Developer',
    resume_url: '#',
    status: 'new',
    created_at: '2026-08-17T09:00:00Z',
  },
  {
    id: '2',
    name: 'Mohammed Al Farsi',
    email: 'm.alfarsi@outlook.com',
    phone: '+971 55 987 6543',
    position: 'Cloud Solutions Architect',
    resume_url: '#',
    status: 'reviewed',
    created_at: '2026-08-14T13:00:00Z',
  },
];

export const MOCK_MEDIA = [
  {
    id: '1',
    url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400',
    filename: 'salesforce-dashboard.jpg',
    alt_text: 'Salesforce CRM dashboard view',
    uploaded_at: '2026-08-10T09:00:00Z',
  },
  {
    id: '2',
    url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400',
    filename: 'analytics-chart.jpg',
    alt_text: 'Business analytics chart',
    uploaded_at: '2026-08-05T10:00:00Z',
  },
  {
    id: '3',
    url: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=400',
    filename: 'team-meeting.jpg',
    alt_text: 'Team collaboration meeting',
    uploaded_at: '2026-08-01T08:00:00Z',
  },
];

export const MOCK_REDIRECTS = [
  {
    id: '1',
    old_url: '/services/crm',
    new_url: '/services',
    type: 301,
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: '2',
    old_url: '/blog',
    new_url: '/blogs',
    type: 301,
    created_at: '2026-07-15T00:00:00Z',
  },
];
